### PR TITLE
fix: Cean up of `package_analyses` table.

### PR DESCRIPTION
**Pull request by rafiu007**
Updated the clean up of package_worker_results table to use foreign key for clean up.This will make sure we clean same records for package_analyses table as well.

### CODE REVIEW

**Review by deepak1725 — COMMENTED** [review]
I'm. not sure why we are dealing with Foreign keys like this. Ideally i would prefer to modify Table Properties itself to CASCADE Delete.

In This way, when we delete some record which has foreign key reference, all others tables records which has Foreign Key reference to this table will either get DELETED or Set as Null based on our Settings.

More on https://www.sqlservertutorial.net/sql-server-basics/sql-server-foreign-key/#:~:text=ON%20DELETE%20SET%20DEFAULT%20SQL,if%20no%20default%20value%20specified. 

I'm open to any new thoughts that i'm probably missing here.

**Comment by rafiu007** [comment]
package_analyses is the parent table and we are deleting package worker results with foreign key as otherwise some references are remianing and while cleaning package_analyses ,it fails with foreignkey violation.

**Comment by deepak1725** [comment]
> package_analyses is the parent table and we are deleting package worker results with foreign key as otherwise some references are remianing and while cleaning package_analyses ,it fails with foreignkey violation.

Thats is understandable from code. Any reason for Not Using CASCADE DELETE or ON DELETE property of SQL Tables here..?

**Comment by prashbnair** [comment]
> I'm not sure why we are dealing with Foreign keys like this. Ideally i would prefer to modify Table Properties itself to CASCADE Delete.

This is option that should be tried out.

**Comment by rafiu007** [comment]
I have tried out cascade and since it uses orm we will need to change a lot of queries thatwe use to delete data,owing to this,its is better to stick to this pr.

**Review by prashbnair — APPROVED** [review]

**Pull request merged**
