### PR TITLE
temp fix for retraining bug

### PR DESCRIPTION
**Pull request by anuragtr**

### CODE REVIEW

**Comment by tisnik** [comment]
@anuragtr does it mean that the condition will be always True?

**Comment by anuragtr** [comment]
@tisnik yes, because of this condition, retraining will trigger daily (if at least 1 stack got added on previous day)

**Comment by tisnik** [comment]
Ok thanks @anuragtr . Then it might be better to remove line 399 with (now improper) comment and remove the condition as well

**Comment by tisnik** [comment]
[test]

**Comment by anuragtr** [comment]
@tisnik I wanted to make minimal changes to code so that the structure stays intact for future reference and to make it easy for anyone to understand what the temporary fix is. hope the reasoning is fine :)

**Comment by anuragtr** [comment]
removed [WIP] and merging @miteshvp

**Comment by tisnik** [comment]
@anuragtr well, it is a bit misleading as the error is not referenced and now the two consecutive comments together does not make much sense. But it is merged already...

**Pull request merged**
